### ISSUE TITLE
Ability to provide openapi repo tag

### ISSUE THREAD

**Issue by rlratcliffe** [MS3Inc/tavros-jenkins-quickstarts#7]
Moving this one over from gitea from @jam01 

So I think following the api sdlc devs should reach a point where they can commit to an api document before starting implementation... at that point they should tag that api, probably with something like 0.1 or something, doesn't matter... The point is that they may want to start a new project from a specific version of the api, ie a tag.

As for the implementation, I'm thinking either another field for that tag name, or depending on the method to pull (either manual or through jenkins steps) we ask them to send in the entire argument necessary... might be a url with a tag specified or some other URI...

**Comment by rlratcliffe** [comment]
This also relates to #6

**Comment by rlratcliffe** [comment]
I've got this sort of working through a parameter and jenkins steps but need to figure out if there's a way to specify a branch along with the tag. For example, having it set to only use tags on the main branch?

**Comment by jam01** [comment]
tags are branch independent

**Comment by rlratcliffe** [comment]
I could have phrased this better. I meant from a design perspective if we only wanted to allow creating repos of tags that are on main, but that doesn't seem necessary the more I think about in. In the future maybe we can implement checkout based on branch, but for now if no tag is supplied it will default to pulling from main.
